routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
use Mcamara\LaravelLocalization\Facades\LaravelLocalization;

/**
 * Sitemap
 */
Route::as('sitemap.')->group(function () {
    Route::get('sitemap.xml', 'SitemapController@index')->name('index');
    Route::get('sitemap-categories.xml', 'SitemapController@categories')->name('categories');
    Route::get('sitemap-servers.xml', 'SitemapController@servers')->name('servers');
    Route::get('sitemap-server-posts.xml', 'SitemapController@serverPosts')->name('server.posts');
});

/**
 * Localize this routes.
 */
Route::group(['prefix' => LaravelLocalization::setLocale(), 'middleware' => 'localization'], function () {
    /**
     * Auth
     */
    Auth::routes(['verify' => true]);

    /**
     * Admin
     */
    Route::group([
        'prefix' => 'admin',
        'as' => 'admin.',
        'namespace' => 'Admin',
        'middleware' => ['auth', 'auth.admin']
    ], function () {
        /**
         * Overview
         */
        Route::get('', 'OverviewController@index')->name('overview');

        /**
         * Servers
         */
        Route::group(['prefix' => 'servers', 'as' => 'servers.'], function () {
            Route::get('', 'ServerController@index')->name('index');

            Route::group(['prefix' => '{server}'], function () {
                Route::put('toggle-suspended', 'ServerController@toggleSuspended')->name('toggle_suspended');
                Route::put('toggle-sponsored', 'ServerController@toggleSponsored')->name('toggle_sponsored');
            });
        });

        /**
         * Settings
         */
        Route::group(['prefix' => 'settings', 'as' => 'settings.'], function () {
            Route::get('', 'SettingsController@index')->name('index');
            Route::post('store', 'SettingsController@store')->name('store');
        });
    });

    /**
     * Servers
     */
    Route::as('servers.')->group(function () {
        /**
         * Server detail
         */
        Route::prefix('server/{server}')->as('show')->group(function () {
            Route::get('/', 'ServerController@show');
            Route::get('banner.png', 'ServerController@banner')->name('.banner');
        });

        /**
         * Create & Store
         */
        Route::middleware('auth')->get('create', 'ServerController@create')->name('create');
        Route::middleware('auth')->post('store', 'ServerController@store')->name('store');

        /**
         * Servers
         */
        Route::get('servers/{params?}', 'ServerController@index')->name('index');
        Route::get('{params?}', 'RedirectController@index'); // @TEMP
    });

    /**
     * Blog
     */
    Route::get('blog/servers/{blog}', 'BlogController@redirect');
    Route::get('servers/blog/{blog}', 'BlogController@show')->name('servers.blog.show');
});

resources/views/blog.blade.php
@extends('servers.layouts.master')

@section('content')
<div class="container py-4">
    <h1 class="section-title h4">{{ $page['title'] }}</h1>
    <p class="w-50 text-muted">{{ $page['description'] }}</p>
    <div class="row">
        <div class="col-lg-8">
            <section class="pb-4">
                @foreach ($servers as $server)
                    <div class="card mb-3">
                        <div class="card-body">
                            <div class="d-flex align-items-center justify-content-between mb-3">
                                <h3 class="h5 mb-0">
                                    <a href="{{ route('servers.show', $server->slug) }}" class="text-light">{{ $loop->iteration }}. {{ $server->name }}</a>
                                </h3>
                                <div class="d-inline-block btn-sm box-round border border-primary">
                                    <div class="text-truncate">
                                        <span class="font-weight-bold">{{ number_format($server->online_players) }}</span>
                                        <span class="text-muted mx-1">/</span>
                                        <span class="text-muted">{{ number_format($server->max_players) }}</span>
                                    </div>
                                </div>
                            </div>
                            <div class="server-description small mb-3">{{ $server->formatDescription(200) }}</div>
                            <a href="{{ route('servers.show', $server->slug) }}">
                                <img class="img-responsive rounded" src="{{ route('servers.show.banner', $server->slug) }}" alt="Server banner">
                            </a>
                        </div>
                    </div>
                @endforeach
            </section>
        </div>
        <div class="col-lg-4">
            <div class="btn-filter-group mb-3">
                @foreach ($posts as $post)
                    <a href="{{ $post['url'] }}" class="w-100 d-flex align-items-center justify-content-between btn btn-{{ $post['mode_id'] === $mode->id ? 'success' : 'dark-2' }}">
                        <div class="text-truncate">{{ $post['title'] }}</div>
                        <span class="server-count">{{ $post['servers_count'] }}</span>
                    </a>
                @endforeach
            </div>
        </div>
    </div>
</div>
@endsection