routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
use Mcamara\LaravelLocalization\Facades\LaravelLocalization;

/**
 * Sitemap
 */
Route::as('sitemap.')->group(function () {
    Route::get('sitemap.xml', 'SitemapController@index')->name('index');
    Route::get('sitemap-categories.xml', 'SitemapController@categories')->name('categories');
    Route::get('sitemap-servers.xml', 'SitemapController@servers')->name('servers');
    Route::get('sitemap-server-posts.xml', 'SitemapController@serverPosts')->name('server.posts');
});

/**
 * Localize this routes.
 */
Route::group(['prefix' => LaravelLocalization::setLocale(), 'middleware' => 'localization'], function () {
    /**
     * Auth
     */
    Auth::routes(['verify' => true]);

    /**
     * Admin
     */
    Route::group([
        'prefix' => 'admin',
        'as' => 'admin.',
        'namespace' => 'Admin',
        'middleware' => ['auth', 'auth.admin']
    ], function () {
        /**
         * Overview
         */
        Route::get('', 'OverviewController@index')->name('overview');

        /**
         * Servers
         */
        Route::group(['prefix' => 'servers', 'as' => 'servers.'], function () {
            Route::get('', 'ServerController@index')->name('index');

            Route::group(['prefix' => '{server}'], function () {
                Route::put('toggle-suspended', 'ServerController@toggleSuspended')->name('toggle_suspended');
                Route::put('toggle-sponsored', 'ServerController@toggleSponsored')->name('toggle_sponsored');
            });
        });

        /**
         * Settings
         */
        Route::group(['prefix' => 'settings', 'as' => 'settings.'], function () {
            Route::get('', 'SettingsController@index')->name('index');
            Route::post('store', 'SettingsController@store')->name('store');
        });
    });

    /**
     * Servers
     */
    Route::as('servers.')->group(function () {
        /**
         * Server detail
         */
        Route::prefix('server/{server}')->as('show')->group(function () {
            Route::get('/', 'ServerController@show');
            Route::get('banner.png', 'ServerController@banner')->name('.banner');
        });

        /**
         * Create & Store
         */
        Route::middleware('auth')->get('create', 'ServerController@create')->name('create');
        Route::middleware('auth')->post('store', 'ServerController@store')->name('store');

        /**
         * Servers
         */
        Route::get('servers/{params?}', 'ServerController@index')->name('index');
        Route::get('{params?}', 'RedirectController@index'); // @TEMP
    });

    /**
     * Blog
     */
    Route::get('blog/servers/{blog}', 'BlogController@redirect');
    Route::get('servers/blog/{blog}', 'BlogController@show')->name('servers.blog.show');
});

app/Models/Server.php
<?php

namespace App\Models;

use App\Components\Country;
use App\Components\Str;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\HtmlString;

class Server extends Model
{
    protected $fillable = [
        'name',
        'slug',
        'server_ip',
        'server_original_ip',
        'server_port',
        'description',
        'motd',
        'country',
        'online_players',
        'max_players',
        'favicon',
        'website_url',
        'discord_url',
        'video_url',
        'votifier_enabled',
        'votifier_ip',
        'votifier_port',
        'votifier_public_key',
        'is_sponsored',
        'is_suspended',
        'pinged_at',
        'offline_at',
    ];

    protected $casts = [
        'is_sponsored' => 'boolean',
        'is_suspended' => 'boolean',
        'server_port' => 'integer',
        'online_players' => 'integer',
        'max_players' => 'integer',
    ];

    protected $dates = [
        'pinged_at',
        'offline_at',
    ];

    public function createdBy()
    {
        return $this->belongsTo(User::class, 'created_by');
    }

    public function modes()
    {
        return $this->belongsToMany(Mode::class);
    }

    public function versions()
    {
        return $this->belongsToMany(Version::class);
    }

    public function scopeWhereOnline($query)
    {
        return $query->whereNull('offline_at');
    }

    public function scopeWhereOffline($query)
    {
        return $query->whereNotNull('offline_at');
    }

    public function scopeWhereTrackingServers($query)
    {
        return $query->whereOnline()->orWhereDate('offline_at', '>', today()->subDays(30));
    }

    public function scopeWhereSponsored($query)
    {
        return $query->where('is_sponsored', true);
    }

    public function scopeWhereNotSponsored($query)
    {
        return $query->where('is_sponsored', false);
    }

    public function scopeWhereSuspended($query)
    {
        return $query->where('is_suspended', true);
    }

    public function scopeWhereNotSuspended($query)
    {
        return $query->where('is_suspended', false);
    }

    public function country()
    {
        return Country::get()->where('code', $this->country)->first();
    }

    public function ipAndPort()
    {
        return $this->server_ip . ($this->server_port !== 25565 ? ":{$this->server_port}" : null);
    }

    public function isOnline()
    {
        return is_null($this->offline_at);
    }

    public function formatDescription(?int $limit = null)
    {
        if ($limit > 0) {
            $description =  Str::limit($this->description, $limit);
        }

        $description = preg_replace("/(?=\>\s+\n|\n)+(\s+)/", "\n", $description ?? $this->description);
        $description = array_map(fn ($paragraph) => '<p>' . e($paragraph, false) . '</p>', explode("\n", $description));

        return new HtmlString(implode("\n", $description));
    }

    public function formatMotd()
    {
        return new HtmlString(
            nl2br(Str::formatMinecraftColor(e($this->motd, false)))
        );
    }

    public function faviconPath()
    {
        return storage_path("app/public/favicons/{$this->id}{$this->favicon}.png");
    }

    public function faviconUrl()
    {
        return asset("storage/favicons/{$this->id}{$this->favicon}.png");
    }

    public function firstVersion()
    {
        return $this->versions->first();
    }
}

app/Http/Controllers/Admin/ServerController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Components\LSEO;
use App\Models\Server;
use Illuminate\Http\Request;

class ServerController
{
    public function index(Request $request)
    {
        $servers = Server::select([
            'id', 'name', 'slug', 'server_ip', 'server_port',
            'online_players', 'max_players', 'is_sponsored', 'is_suspended',
            'created_at', 'offline_at'
        ])
            ->latest('created_at');

        if ($request->has('q')) {
            $servers->where('name', 'like', "%{$request->q}%");
        }

        if ($request->has('sponsored')) {
            $servers->where('is_sponsored', (bool) $request->sponsored);
        }

        if ($request->has('suspended')) {
            $servers->where('is_suspended', (bool) $request->suspended);
        }

        $servers = $servers->paginate(25);

        LSEO::setTitle(__('Servers'));

        return view('admin.servers.index', compact(
            'servers'
        ));
    }

    public function toggleSuspended($id)
    {
        $server = Server::select('id', 'is_suspended')->findOrFail($id);

        $server->is_suspended = !$server->is_suspended;

        $server->save();

        return back();
    }

    public function toggleSponsored($id)
    {
        $server = Server::select('id', 'is_sponsored')->findOrFail($id);

        $server->is_sponsored = !$server->is_sponsored;

        $server->save();

        return back();
    }
}

app/Http/Controllers/ServerController.php
<?php

namespace App\Http\Controllers;

use Image;
use App\Components\LSEO;
use App\Components\Country;
use App\Components\Minecraft;
use App\Components\Str;
use App\Http\Requests\StoreServerRequest;
use App\Jobs\CheckServer;
use App\Models\Mode;
use App\Models\Server;
use App\Models\Version;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Cache;

class ServerController
{
    public function index(Request $request, $params = null)
    {
        $trackingServersCount = Server::whereNotSuspended()
            ->whereTrackingServers()
            ->count();

        $servers = Server::whereNotSuspended()
            ->with(['modes', 'versions'])
            ->select([
                'id', 'name', 'slug', 'server_ip', 'server_port',
                'country', 'online_players', 'max_players',
                'favicon', 'offline_at',
            ])
            ->latest('online_players');

        $activeParamsCount = 0;
        $params = $params ? explode(':', $params) : [];

        $modeParam = Mode::select('id', 'name', 'slug')
            ->whereIn('slug', $params)
            ->first();

        if ($modeParam) {
            $servers->whereHas('modes', function ($query) use ($modeParam) {
                $query->where('modes.id', $modeParam->id);
            });

            $activeParamsCount++;
        }

        $allCountries = Country::get();

        $countryParam = $allCountries->filter(function ($country) use ($params) {
            return in_array($country->code, $params);
        })->first();

        if ($countryParam) {
            $servers->where('country', $countryParam->code);

            $activeParamsCount++;
        }

        if ($activeParamsCount !== count($params)) {
            return abort(404);
        }

        if ($request->has('q')) {
            $servers->where(function ($query) use ($request) {
                $query->where('server_ip', 'like', "%{$request->q}%")->orWhere('name', 'like', "%{$request->q}%");
            });
        }

        $serverCountries = ($modeParam ? $modeParam->servers() : new Server)
            ->select('country')
            ->whereNotSuspended()
            ->whereNotNull('country')
            ->pluck('country')
            ->unique()
            ->toArray();

        $countries = $allCountries->filter(function ($country) use ($serverCountries) {
            return in_array($country->code, $serverCountries);
        });

        $modes = Mode::select('name', 'slug')
            ->withCount(['servers' => function ($query) use ($countryParam) {
                if ($countryParam) {
                    $query->where('country', $countryParam->code);
                }
            }])
            ->having('servers_count', '>', 0)
            ->get();

        $servers = $servers->paginate();
        $totalServers = ['servers' => number_format($servers->total())];

        if ($countryParam && $modeParam) {
            $pageTransParams = ['mode' => $modeParam->name, 'country' => $countryParam->name];

            $page = [
                'title' => __('Minecraft :mode Servers in :country', $pageTransParams),
                'description' => __('Find Minecraft :mode Servers for :country. There are :servers active servers here.', $pageTransParams + $totalServers),
            ];
        } elseif ($countryParam) {
            $page = [
                'title' => __('Minecraft Servers in :country', ['country' => $countryParam->name]),
                'description' => __('Find Minecraft Servers for :country. There are :servers active servers here.', ['country' => $countryParam->name] + $totalServers),
            ];
        } elseif ($modeParam) {
            $page = [
                'title' => __('Minecraft :mode Servers', ['mode' => $modeParam->name]),
                'description' => __('Find Minecraft :mode Servers. There are :servers active servers here.', ['mode' => $modeParam->name] + $totalServers),
            ];
        } else {
            $page = [
                'title' => __('Minecraft Servers'),
                'description' => __('Find the best Minecraft servers with our multiplayer server list. Browse detailed information on each server and vote for your favourite.'),
                'set_title' => false,
            ];

            LSEO::setTitle('{sitename} {separator} {slogan}', false);
        }

        if ($page['set_title'] ?? true) {
            LSEO::setTitle($page['title']);
        }

        LSEO::setDescription($page['description']);

        LSEO::setCanonical(
            route(
                'servers.index',
                implode(':', array_filter([$countryParam ? $countryParam->code : null, $modeParam ? $modeParam->slug : null]))
            )
        );

        return view('servers.index', compact(
            'trackingServersCount',
            'servers',
            'modes',
            'countries',
            'params',
            'modeParam',
            'countryParam',
            'page'
        ));
    }

    public function show($slug)
    {
        $server = Server::select([
            'id', 'name', 'description', 'slug', 'server_ip', 'server_port',
            'country', 'online_players', 'max_players', 'pinged_at', 'website_url',
            'discord_url', 'video_url', 'favicon', 'motd', 'offline_at'
        ])
            ->whereNotSuspended()
            ->where('slug', $slug)
            ->firstOrFail();

        if ($server->pinged_at < now()->subMinutes(10)) {
            CheckServer::dispatch($server);

            return redirect()->refresh();
        }

        LSEO::setTitle($server->name);

        LSEO::setDescription(__(":name. :modes. Up to :max players. :status now.", [
            'name' => $server->name,
            'modes' => $server->modes->pluck('name')->join(', '),
            'max' => number_format($server->max_players),
            'status' => $server->isOnline() ? __('Available') : __('Unavailable'),
        ]));

        LSEO::setCanonical(
            route('servers.show', $slug)
        );

        return view('servers.show', compact(
            'server'
        ));
    }

    public function banner($slug)
    {
        return Cache::remember("banners.{$slug}", now()->addHour(), function () use ($slug) {
            $server = Server
                ::select([
                    'id', 'name', 'server_ip', 'server_port',
                    'online_players', 'max_players',
                    'country', 'favicon', 'offline_at'
                ])
                ->with(['modes' => function ($query) {
                    $query->select('modes.id', 'name');
                }])
                ->where('slug', $slug)
                ->firstOrFail();

            $onlinePlayers = number_format($server->online_players);
            $maxPlayers = number_format($server->max_players);

            $image = Image::make(resource_path('images/mc-banner-1-540x90.png'));

            $image->blur(3);

            if ($server->favicon) {
                $faviconPosition = 13;
                $faviconWidth = 64;

                $image->insert($server->faviconPath(), 'left-center', $faviconPosition);
            }

            $startPosition = $server->favicon ? ($faviconPosition + $faviconWidth + 10) : 13;

            $texts = [
                [
                    'x' => $startPosition, 'y' => 13,
                    'value' => Str::limit($server->name, 17),
                    'size' => 30,
                    'valign' => 'top',
                    'color' => '#fff',
                    'shadow' => true,
                    'weight' => 'bold',
                ],
                [
                    'x' => $startPosition, 'y' => 44,
                    'value' => $server->ipAndPort(),
                    'size' => 18,
                    'color' => '#fff',
                    'shadow' => true,
                    'valign' => 'top',
                ],
                [
                    'x' => $startPosition, 'y' => 76,
                    'value' => Str::limit($server->modes->pluck('name')->join(' | '), 63),
                    'size' => 14,
                    'color' => '#fff',
                    'shadow' => true,
                ],
                [
                    'x' => 527, 'y' => 13,
                    'value' => $server->isOnline() ? __('Online') : __('Offline'),
                    'size' => 15,
                    'color' => $server->isOnline() ? '#28a745' : '#dc3545',
                    'shadow' => [0, 0, 0, .3],
                    'align' => 'right',
                    'valign' => 'top',
                    'weight' => 'bold',
                ],
                [
                    'x' => 527, 'y' => 32,
                    'value' => "{$onlinePlayers}/{$maxPlayers}",
                    'size' => 14,
                    'color' => '#fff',
                    'shadow' => true,
                    'align' => 'right',
                    'valign' => 'top',
                ]
            ];

            if ($server->country) {
                $texts[] = [
                    'x' => 527, 'y' => 76,
                    'value' => Str::upper($server->country()->code),
                    'size' => 14,
                    'color' => '#fff',
                    'shadow' => true,
                    'align' => 'right',
                ];
            }

            foreach ($texts as $text) {
                $text['weight'] = $text['weight'] ?? 'regular';

                if ($text['shadow'] ?? false) {
                    $image->text($text['value'], $text['x'], $text['y'] + 2, function ($font) use ($text) {
                        $font->file(resource_path("fonts/google/google-{$text['weight']}.ttf"));
                        $font->size($text['size']);

                        if ($text['valign'] ?? false) {
                            $font->valign($text['valign']);
                        }

                        if ($text['align'] ?? false) {

resources/views/admin/servers/index.blade.php
@extends('admin.layouts.master')

@section('content')
<div class="wrapper">
    <div class="container">
        <div class="row">
            <div class="col-lg-8">
                <div class="card">
                    <table class="table table-hover mb-0">
                        <thead>
                            <tr>
                                <th colspan="2">{{ __('Server') }}</th>
                                <th>{{ __('Players') }}</th>
                                <th>{{ __('Created at') }}</th>
                                <th></th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach ($servers as $server)
                            <tr>
                                <td class="td-circle">
                                    <span class="circle bg-{{ $server->isOnline() ? 'success' : 'danger' }}"
                                        data-toggle="tooltip"
                                        title="{{ $server->isOnline() ? __('Online') : __('Offline') }}"></span>
                                </td>
                                <td>
                                    @if ($server->is_suspended)
                                    {{ $server->name }}
                                    @else
                                    <a class="text-dark" href="{{ route('servers.show', $server->slug) }}"
                                        target="_blank">{{ $server->name }}</a>
                                    @endif
                                    <div style="margin-top: -8px;">
                                        @if ($server->is_sponsored)
                                        <span class="small text-primary">{{ __('Sponsored') }}</span>
                                        @endif
                                        @if ($server->is_suspended)
                                        <span class="small text-muted">{{ __('Suspended') }}</span>
                                        @endif
                                    </div>
                                </td>
                                <td>
                                    {{ number_format($server->online_players) }}/{{ number_format($server->max_players) }}
                                </td>
                                <td>
                                    <span data-toggle="tooltip"
                                        title="{{ $server->created_at->format('Y-m-d H:i') }}">{{ $server->created_at->diffForHumans() }}</span>
                                </td>
                                <td>
                                    <div class="dropdown">
                                        <button type="button" class="btn btn-sm btn-outline-secondary"
                                            data-toggle="dropdown" style="line-height: .8;">
                                            <svg class="bi bi-three-dots" width="1em" height="1em" viewBox="0 0 16 16"
                                                fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                                                <path fill-rule="evenodd"
                                                    d="M3 9.5a1.5 1.5 0 110-3 1.5 1.5 0 010 3zm5 0a1.5 1.5 0 110-3 1.5 1.5 0 010 3zm5 0a1.5 1.5 0 110-3 1.5 1.5 0 010 3z"
                                                    clip-rule="evenodd" />
                                            </svg>
                                        </button>
                                        <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                                            <a class="dropdown-item" href="#"
                                                onclick="return toggleServer('suspended', {{ $server->id }});">
                                                {{ $server->is_suspended ? __('Activate server') : __('Hide server') }}
                                            </a>
                                            <div class="dropdown-divider"></div>
                                            <a class="dropdown-item" href="#"
                                                onclick="return toggleServer('sponsored', {{ $server->id }});">
                                                {{ $server->is_sponsored ? __('Remove sponsorship') : __('Make a sponsor') }}
                                            </a>
                                        </div>
                                    </div>
                                </td>
                            </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>
                <div class="mt-3 mb-1">
                    <div class="table-responsive">
                        {{ $servers->onEachSide(2)->withQueryString()->links() }}
                    </div>
                </div>
            </div>
            <div class="col-lg-4">
                <div class="card card-body">
                    <form method="GET" action="{{ route('admin.servers.index') }}">
                        <div class="form-group">
                            <input type="text" name="q" class="form-control" placeholder="{{ __('Search...') }}"
                                value="{{ request('q') }}">
                        </div>
                        <div class="form-group">
                            <div class="row">
                                <div class="col-6">
                                    <div class="custom-control custom-checkbox">
                                        <input type="checkbox" name="sponsored" class="custom-control-input"
                                            id="filter-sponsored" {{ request('sponsored') === 'on' ? 'checked' : '' }}>
                                        <label class="custom-control-label"
                                            for="filter-sponsored">{{ __('Sponsored') }}</label>
                                    </div>
                                </div>
                                <div class="col-6">
                                    <div class="custom-control custom-checkbox">
                                        <input type="checkbox" name="suspended" class="custom-control-input"
                                            id="filter-suspended" {{ request('suspended') === 'on' ? 'checked' : '' }}>
                                        <label class="custom-control-label"
                                            for="filter-suspended">{{ __('Suspended') }}</label>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <button type="submit" class="btn btn-primary">{{ __('Search') }}</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
<form id="toggle-suspended-form" method="POST" action="{{ route('admin.servers.toggle_suspended', ':id') }}">
    @csrf
    @method('PUT')
</form>
<form id="toggle-sponsored-form" method="POST" action="{{ route('admin.servers.toggle_sponsored', ':id') }}">
    @csrf
    @method('PUT')
</form>
@endsection

@push('scripts')
<script>
    var toggleServer = function (action, id) {
        var $form = $('#toggle-' + action + '-form');

        $form.attr('action', $form.attr('action').replace(':id', id));
        
        $form.submit();

        return false;
    };
</script>
@endpush