routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
use Mcamara\LaravelLocalization\Facades\LaravelLocalization;

/**
 * Sitemap
 */
Route::as('sitemap.')->group(function () {
    Route::get('sitemap.xml', 'SitemapController@index')->name('index');
    Route::get('sitemap-categories.xml', 'SitemapController@categories')->name('categories');
    Route::get('sitemap-servers.xml', 'SitemapController@servers')->name('servers');
    Route::get('sitemap-server-posts.xml', 'SitemapController@serverPosts')->name('server.posts');
});

/**
 * Localize this routes.
 */
Route::group(['prefix' => LaravelLocalization::setLocale(), 'middleware' => 'localization'], function () {
    /**
     * Auth
     */
    Auth::routes(['verify' => true]);

    /**
     * Admin
     */
    Route::group([
        'prefix' => 'admin',
        'as' => 'admin.',
        'namespace' => 'Admin',
        'middleware' => ['auth', 'auth.admin']
    ], function () {
        /**
         * Overview
         */
        Route::get('', 'OverviewController@index')->name('overview');

        /**
         * Servers
         */
        Route::group(['prefix' => 'servers', 'as' => 'servers.'], function () {
            Route::get('', 'ServerController@index')->name('index');

            Route::group(['prefix' => '{server}'], function () {
                Route::put('toggle-suspended', 'ServerController@toggleSuspended')->name('toggle_suspended');
                Route::put('toggle-sponsored', 'ServerController@toggleSponsored')->name('toggle_sponsored');
            });
        });

        /**
         * Settings
         */
        Route::group(['prefix' => 'settings', 'as' => 'settings.'], function () {
            Route::get('', 'SettingsController@index')->name('index');
            Route::post('store', 'SettingsController@store')->name('store');
        });
    });

    /**
     * Servers
     */
    Route::as('servers.')->group(function () {
        /**
         * Server detail
         */
        Route::prefix('server/{server}')->as('show')->group(function () {
            Route::get('/', 'ServerController@show');
            Route::get('banner.png', 'ServerController@banner')->name('.banner');
        });

        /**
         * Create & Store
         */
        Route::middleware('auth')->get('create', 'ServerController@create')->name('create');
        Route::middleware('auth')->post('store', 'ServerController@store')->name('store');

        /**
         * Servers
         */
        Route::get('servers/{params?}', 'ServerController@index')->name('index');
        Route::get('{params?}', 'RedirectController@index'); // @TEMP
    });

    /**
     * Blog
     */
    Route::get('blog/servers/{blog}', 'BlogController@redirect');
    Route::get('servers/blog/{blog}', 'BlogController@show')->name('servers.blog.show');
});

app/Models/Server.php
<?php

namespace App\Models;

use App\Components\Country;
use App\Components\Str;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\HtmlString;

class Server extends Model
{
    protected $fillable = [
        'name',
        'slug',
        'server_ip',
        'server_original_ip',
        'server_port',
        'description',
        'motd',
        'country',
        'online_players',
        'max_players',
        'favicon',
        'website_url',
        'discord_url',
        'video_url',
        'votifier_enabled',
        'votifier_ip',
        'votifier_port',
        'votifier_public_key',
        'is_sponsored',
        'is_suspended',
        'pinged_at',
        'offline_at',
    ];

    protected $casts = [
        'is_sponsored' => 'boolean',
        'is_suspended' => 'boolean',
        'server_port' => 'integer',
        'online_players' => 'integer',
        'max_players' => 'integer',
    ];

    protected $dates = [
        'pinged_at',
        'offline_at',
    ];

    public function createdBy()
    {
        return $this->belongsTo(User::class, 'created_by');
    }

    public function modes()
    {
        return $this->belongsToMany(Mode::class);
    }

    public function versions()
    {
        return $this->belongsToMany(Version::class);
    }

    public function scopeWhereOnline($query)
    {
        return $query->whereNull('offline_at');
    }

    public function scopeWhereOffline($query)
    {
        return $query->whereNotNull('offline_at');
    }

    public function scopeWhereTrackingServers($query)
    {
        return $query->whereOnline()->orWhereDate('offline_at', '>', today()->subDays(30));
    }

    public function scopeWhereSponsored($query)
    {
        return $query->where('is_sponsored', true);
    }

    public function scopeWhereNotSponsored($query)
    {
        return $query->where('is_sponsored', false);
    }

    public function scopeWhereSuspended($query)
    {
        return $query->where('is_suspended', true);
    }

    public function scopeWhereNotSuspended($query)
    {
        return $query->where('is_suspended', false);
    }

    public function country()
    {
        return Country::get()->where('code', $this->country)->first();
    }

    public function ipAndPort()
    {
        return $this->server_ip . ($this->server_port !== 25565 ? ":{$this->server_port}" : null);
    }

    public function isOnline()
    {
        return is_null($this->offline_at);
    }

    public function formatDescription(?int $limit = null)
    {
        if ($limit > 0) {
            $description =  Str::limit($this->description, $limit);
        }

        $description = preg_replace("/(?=\>\s+\n|\n)+(\s+)/", "\n", $description ?? $this->description);
        $description = array_map(fn ($paragraph) => '<p>' . e($paragraph, false) . '</p>', explode("\n", $description));

        return new HtmlString(implode("\n", $description));
    }

    public function formatMotd()
    {
        return new HtmlString(
            nl2br(Str::formatMinecraftColor(e($this->motd, false)))
        );
    }

    public function faviconPath()
    {
        return storage_path("app/public/favicons/{$this->id}{$this->favicon}.png");
    }

    public function faviconUrl()
    {
        return asset("storage/favicons/{$this->id}{$this->favicon}.png");
    }

    public function firstVersion()
    {
        return $this->versions->first();
    }
}

app/Http/Controllers/Admin/ServerController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Components\LSEO;
use App\Models\Server;
use Illuminate\Http\Request;

class ServerController
{
    public function index(Request $request)
    {
        $servers = Server::select([
            'id', 'name', 'slug', 'server_ip', 'server_port',
            'online_players', 'max_players', 'is_sponsored', 'is_suspended',
            'created_at', 'offline_at'
        ])
            ->latest('created_at');

        if ($request->has('q')) {
            $servers->where('name', 'like', "%{$request->q}%");
        }

        if ($request->has('sponsored')) {
            $servers->where('is_sponsored', (bool) $request->sponsored);
        }

        if ($request->has('suspended')) {
            $servers->where('is_suspended', (bool) $request->suspended);
        }

        $servers = $servers->paginate(25);

        LSEO::setTitle(__('Servers'));

        return view('admin.servers.index', compact(
            'servers'
        ));
    }

    public function toggleSuspended($id)
    {
        $server = Server::select('id', 'is_suspended')->findOrFail($id);

        $server->is_suspended = !$server->is_suspended;

        $server->save();

        return back();
    }

    public function toggleSponsored($id)
    {
        $server = Server::select('id', 'is_sponsored')->findOrFail($id);

        $server->is_sponsored = !$server->is_sponsored;

        $server->save();

        return back();
    }
}

app/Http/Controllers/ServerController.php
<?php

namespace App\Http\Controllers;

use Image;
use App\Components\LSEO;
use App\Components\Country;
use App\Components\Minecraft;
use App\Components\Str;
use App\Http\Requests\StoreServerRequest;
use App\Jobs\CheckServer;
use App\Models\Mode;
use App\Models\Server;
use App\Models\Version;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Cache;

class ServerController
{
    public function index(Request $request, $params = null)
    {
        $trackingServersCount = Server::whereNotSuspended()
            ->whereTrackingServers()
            ->count();

        $servers = Server::whereNotSuspended()
            ->with(['modes', 'versions'])
            ->select([
                'id', 'name', 'slug', 'server_ip', 'server_port',
                'country', 'online_players', 'max_players',
                'favicon', 'offline_at',
            ])
            ->latest('online_players');

        $activeParamsCount = 0;
        $params = $params ? explode(':', $params) : [];

        $modeParam = Mode::select('id', 'name', 'slug')
            ->whereIn('slug', $params)
            ->first();

        if ($modeParam) {
            $servers->whereHas('modes', function ($query) use ($modeParam) {
                $query->where('modes.id', $modeParam->id);
            });

            $activeParamsCount++;
        }

        $allCountries = Country::get();

        $countryParam = $allCountries->filter(function ($country) use ($params) {
            return in_array($country->code, $params);
        })->first();

        if ($countryParam) {
            $servers->where('country', $countryParam->code);

            $activeParamsCount++;
        }

        if ($activeParamsCount !== count($params)) {
            return abort(404);
        }

        if ($request->has('q')) {
            $servers->where(function ($query) use ($request) {
                $query->where('server_ip', 'like', "%{$request->q}%")->orWhere('name', 'like', "%{$request->q}%");
            });
        }

        $serverCountries = ($modeParam ? $modeParam->servers() : new Server)
            ->select('country')
            ->whereNotSuspended()
            ->whereNotNull('country')
            ->pluck('country')
            ->unique()
            ->toArray();

        $countries = $allCountries->filter(function ($country) use ($serverCountries) {
            return in_array($country->code, $serverCountries);
        });

        $modes = Mode::select('name', 'slug')
            ->withCount(['servers' => function ($query) use ($countryParam) {
                if ($countryParam) {
                    $query->where('country', $countryParam->code);
                }
            }])
            ->having('servers_count', '>', 0)
            ->get();

        $servers = $servers->paginate();
        $totalServers = ['servers' => number_format($servers->total())];

        if ($countryParam && $modeParam) {
            $pageTransParams = ['mode' => $modeParam->name, 'country' => $countryParam->name];

            $page = [
                'title' => __('Minecraft :mode Servers in :country', $pageTransParams),
                'description' => __('Find Minecraft :mode Servers for :country. There are :servers active servers here.', $pageTransParams + $totalServers),
            ];
        } elseif ($countryParam) {
            $page = [
                'title' => __('Minecraft Servers in :country', ['country' => $countryParam->name]),
                'description' => __('Find Minecraft Servers for :country. There are :servers active servers here.', ['country' => $countryParam->name] + $totalServers),
            ];
        } elseif ($modeParam) {
            $page = [
                'title' => __('Minecraft :mode Servers', ['mode' => $modeParam->name]),
                'description' => __('Find Minecraft :mode Servers. There are :servers active servers here.', ['mode' => $modeParam->name] + $totalServers),
            ];
        } else {
            $page = [
                'title' => __('Minecraft Servers'),
                'description' => __('Find the best Minecraft servers with our multiplayer server list. Browse detailed information on each server and vote for your favourite.'),
                'set_title' => false,
            ];

            LSEO::setTitle('{sitename} {separator} {slogan}', false);
        }

        if ($page['set_title'] ?? true) {
            LSEO::setTitle($page['title']);
        }

        LSEO::setDescription($page['description']);

        LSEO::setCanonical(
            route(
                'servers.index',
                implode(':', array_filter([$countryParam ? $countryParam->code : null, $modeParam ? $modeParam->slug : null]))
            )
        );

        return view('servers.index', compact(
            'trackingServersCount',
            'servers',
            'modes',
            'countries',
            'params',
            'modeParam',
            'countryParam',
            'page'
        ));
    }

    public function show($slug)
    {
        $server = Server::select([
            'id', 'name', 'description', 'slug', 'server_ip', 'server_port',
            'country', 'online_players', 'max_players', 'pinged_at', 'website_url',
            'discord_url', 'video_url', 'favicon', 'motd', 'offline_at'
        ])
            ->whereNotSuspended()
            ->where('slug', $slug)
            ->firstOrFail();

        if ($server->pinged_at < now()->subMinutes(10)) {
            CheckServer::dispatch($server);

            return redirect()->refresh();
        }

        LSEO::setTitle($server->name);

        LSEO::setDescription(__(":name. :modes. Up to :max players. :status now.", [
            'name' => $server->name,
            'modes' => $server->modes->pluck('name')->join(', '),
            'max' => number_format($server->max_players),
            'status' => $server->isOnline() ? __('Available') : __('Unavailable'),
        ]));

        LSEO::setCanonical(
            route('servers.show', $slug)
        );

        return view('servers.show', compact(
            'server'
        ));
    }

    public function banner($slug)
    {
        return Cache::remember("banners.{$slug}", now()->addHour(), function () use ($slug) {
            $server = Server
                ::select([
                    'id', 'name', 'server_ip', 'server_port',
                    'online_players', 'max_players',
                    'country', 'favicon', 'offline_at'
                ])
                ->with(['modes' => function ($query) {
                    $query->select('modes.id', 'name');
                }])
                ->where('slug', $slug)
                ->firstOrFail();

            $onlinePlayers = number_format($server->online_players);
            $maxPlayers = number_format($server->max_players);

            $image = Image::make(resource_path('images/mc-banner-1-540x90.png'));

            $image->blur(3);

            if ($server->favicon) {
                $faviconPosition = 13;
                $faviconWidth = 64;

                $image->insert($server->faviconPath(), 'left-center', $faviconPosition);
            }

            $startPosition = $server->favicon ? ($faviconPosition + $faviconWidth + 10) : 13;

            $texts = [
                [
                    'x' => $startPosition, 'y' => 13,
                    'value' => Str::limit($server->name, 17),
                    'size' => 30,
                    'valign' => 'top',
                    'color' => '#fff',
                    'shadow' => true,
                    'weight' => 'bold',
                ],
                [
                    'x' => $startPosition, 'y' => 44,
                    'value' => $server->ipAndPort(),
                    'size' => 18,
                    'color' => '#fff',
                    'shadow' => true,
                    'valign' => 'top',
                ],
                [
                    'x' => $startPosition, 'y' => 76,
                    'value' => Str::limit($server->modes->pluck('name')->join(' | '), 63),
                    'size' => 14,
                    'color' => '#fff',
                    'shadow' => true,
                ],
                [
                    'x' => 527, 'y' => 13,
                    'value' => $server->isOnline() ? __('Online') : __('Offline'),
                    'size' => 15,
                    'color' => $server->isOnline() ? '#28a745' : '#dc3545',
                    'shadow' => [0, 0, 0, .3],
                    'align' => 'right',
                    'valign' => 'top',
                    'weight' => 'bold',
                ],
                [
                    'x' => 527, 'y' => 32,
                    'value' => "{$onlinePlayers}/{$maxPlayers}",
                    'size' => 14,
                    'color' => '#fff',
                    'shadow' => true,
                    'align' => 'right',
                    'valign' => 'top',
                ]
            ];

            if ($server->country) {
                $texts[] = [
                    'x' => 527, 'y' => 76,
                    'value' => Str::upper($server->country()->code),
                    'size' => 14,
                    'color' => '#fff',
                    'shadow' => true,
                    'align' => 'right',
                ];
            }

            foreach ($texts as $text) {
                $text['weight'] = $text['weight'] ?? 'regular';

                if ($text['shadow'] ?? false) {
                    $image->text($text['value'], $text['x'], $text['y'] + 2, function ($font) use ($text) {
                        $font->file(resource_path("fonts/google/google-{$text['weight']}.ttf"));
                        $font->size($text['size']);

                        if ($text['valign'] ?? false) {
                            $font->valign($text['valign']);
                        }

                        if ($text['align'] ?? false) {

resources/views/servers/create.blade.php
@extends('servers.layouts.master')

@section('content')
<div class="container py-4">
    <div class="row">
        <div class="col-lg-6 offset-lg-3">
            <form action="{{ route('servers.store') }}" method="post">
                @csrf
                <div class="card mb-3">
                    <div class="card-body">
                        <h1 class="h5 mb-4">{{ __('Add server') }}</h1>
                        <div class="form-group">
                            <div class="row">
                                <div class="col-sm-9">
                                    <input type="text" name="server_ip"
                                        class="form-control @error('server_ip') is-invalid @enderror"
                                        value="{{ old('server_ip') }}" placeholder="{{ __('Server IP or hostname') }}"
                                        autofocus>
                                </div>
                                <div class="col-sm-3">
                                    <input type="text" name="server_port"
                                        class="form-control @error('server_port') is-invalid @enderror"
                                        placeholder="{{ __('Port') }}" value="{{ old('server_port', 25565) }}">
                                </div>
                            </div>
                            @error('server_ip')
                            <span class="invalid-feedback d-block">{{ $message }}</span>
                            @enderror
                            @error('server_port')
                            <span class="invalid-feedback d-block">{{ $message }}</span>
                            @enderror
                        </div>
                        <div class="form-group">
                            <input type="text" name="name" class="form-control @error('name') is-invalid @enderror"
                                placeholder="{{ __('Server name') }}" value="{{ old('name') }}">
                            @error('name')
                            <span class="invalid-feedback d-block">{{ $message }}</span>
                            @enderror
                        </div>
                        <div class="form-group">
                            <select id="country" name="country" placeholder="{{ __('Choose country') }}">
                                <option></option>
                                @foreach ($countries as $country)
                                <option value="{{ $country->code }}"
                                    {{ old('country') === $country->code ? ' selected' : '' }}>
                                    {{ $country->with_native_name }}</option>
                                @endforeach
                            </select>
                            @error('country')
                            <span class="invalid-feedback d-block">{{ $message }}</span>
                            @enderror
                        </div>
                        <div class="form-group">
                            <select id="modes" name="modes[]" placeholder="{{ __('Choose game modes') }}" multiple>
                                @foreach($modes as $mode)
                                <option value="{{ $mode->id }}"
                                    {{ in_array($mode->id, old('modes', [])) ? ' selected' : '' }}>{{ $mode->name }}
                                </option>
                                @endforeach
                            </select>
                            @error('modes')
                            <span class="invalid-feedback d-block">{{ $message }}</span>
                            @enderror
                        </div>
                        <div class="form-footer">
                            <textarea name="description" rows="4"
                                class="form-control @error('description') is-invalid @enderror"
                                placeholder="{{ __('What things do you have on your server? Write in detail...') }}">{{ old('description') }}</textarea>
                            @error('description')
                            <span class="invalid-feedback d-block">{{ $message }}</span>
                            @enderror
                        </div>
                    </div>
                </div>
                <div class="card mb-3">
                    <div class="card-body">
                        <div class="form-group">
                            <h5 class="mb-4">{{ __('Optional fields') }}</h5>
                            <input type="text" name="website_url"
                                class="form-control @error('website_url') is-invalid @enderror"
                                placeholder="{{ __('Website') }}" value="{{ old('website_url') }}">
                            @error('website_url')
                            <span class="invalid-feedback d-block">{{ $message }}</span>
                            @enderror
                        </div>
                        <div class="form-group">
                            <input type="text" name="discord_invite_url"
                                class="form-control @error('discord_invite_url') is-invalid @enderror"
                                placeholder="{{ __('Discord (invite link)') }}" value="{{ old('discord_invite_url') }}">
                            @error('discord_invite_url')
                            <span class="invalid-feedback d-block">{{ $message }}</span>
                            @enderror
                        </div>
                        <div class="form-footer">
                            <input type="text" name="video_url"
                                class="form-control @error('video_url') is-invalid @enderror"
                                placeholder="{{ __('YouTube video link') }}" value="{{ old('video_url') }}">
                            @error('video_url')
                            <span class="invalid-feedback d-block">{{ $message }}</span>
                            @enderror
                        </div>
                    </div>
                </div>
                <div class="card mb-3">
                    <div class="card-body">
                        <h5 class="mb-4">{{ __('Votifier (optional)') }}</h5>
                        <div class="custom-control custom-checkbox">
                            <input type="checkbox" class="custom-control-input" id="votifier_enabled"
                                name="votifier_enabled" {{ old('votifier_enabled') === 'on' ? ' checked' : '' }}>
                            <label class="custom-control-label"
                                for="votifier_enabled">{{ __('Enable votifier') }}</label>
                        </div>
                        <div id="votifier-area" class="mt-3" style="display:none">
                            <div class="form-group">
                                <div class="row">
                                    <div class="col-sm-9">
                                        <input type="text" name="votifier_ip"
                                            class="form-control @error('votifier_ip') is-invalid @enderror"
                                            value="{{ old('votifier_ip') }}"
                                            placeholder="{{ __('Votifier IP or hostname') }}">
                                    </div>
                                    <div class="col-sm-3">
                                        <input type="text" name="votifier_port"
                                            class="form-control @error('votifier_port') is-invalid @enderror"
                                            placeholder="{{ __('Port') }}" value="{{ old('votifier_port', 8192) }}">
                                    </div>
                                </div>
                                @error('votifier_ip')
                                <span class="invalid-feedback d-block">{{ $message }}</span>
                                @enderror
                                @error('votifier_port')
                                <span class="invalid-feedback d-block">{{ $message }}</span>
                                @enderror
                            </div>
                            <div class="form-footer">
                                <textarea name="votifier_public_key" rows="4"
                                    class="form-control @error('votifier_public_key') is-invalid @enderror"
                                    placeholder="{{ __('Votifier public key...') }}">{{ old('votifier_public_key') }}</textarea>
                                @error('votifier_public_key')
                                <span class="invalid-feedback d-block">{{ $message }}</span>
                                @enderror
                            </div>
                        </div>
                    </div>
                </div>
                <div class="card">
                    <div class="card-body">
                        <button type="submit" class="btn btn-dark-2">{{ __('Continue') }}</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
@endsection

@push('scripts')
<script>
    $(function () {
        $('#country').selectize();
        $('#modes').selectize();

        var votifier = function () {
            if ($('#votifier_enabled').prop('checked')) {
                $('#votifier-area').show();
            } else {
                $('#votifier-area').hide();
            }
        };

        $('#votifier_enabled').on('click', function () {
            votifier();
        });

        votifier();
    })
</script>
@endpush