routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
use Mcamara\LaravelLocalization\Facades\LaravelLocalization;

/**
 * Sitemap
 */
Route::as('sitemap.')->group(function () {
    Route::get('sitemap.xml', 'SitemapController@index')->name('index');
    Route::get('sitemap-categories.xml', 'SitemapController@categories')->name('categories');
    Route::get('sitemap-servers.xml', 'SitemapController@servers')->name('servers');
    Route::get('sitemap-server-posts.xml', 'SitemapController@serverPosts')->name('server.posts');
});

/**
 * Localize this routes.
 */
Route::group(['prefix' => LaravelLocalization::setLocale(), 'middleware' => 'localization'], function () {
    /**
     * Auth
     */
    Auth::routes(['verify' => true]);

    /**
     * Admin
     */
    Route::group([
        'prefix' => 'admin',
        'as' => 'admin.',
        'namespace' => 'Admin',
        'middleware' => ['auth', 'auth.admin']
    ], function () {
        /**
         * Overview
         */
        Route::get('', 'OverviewController@index')->name('overview');

        /**
         * Servers
         */
        Route::group(['prefix' => 'servers', 'as' => 'servers.'], function () {
            Route::get('', 'ServerController@index')->name('index');

            Route::group(['prefix' => '{server}'], function () {
                Route::put('toggle-suspended', 'ServerController@toggleSuspended')->name('toggle_suspended');
                Route::put('toggle-sponsored', 'ServerController@toggleSponsored')->name('toggle_sponsored');
            });
        });

        /**
         * Settings
         */
        Route::group(['prefix' => 'settings', 'as' => 'settings.'], function () {
            Route::get('', 'SettingsController@index')->name('index');
            Route::post('store', 'SettingsController@store')->name('store');
        });
    });

    /**
     * Servers
     */
    Route::as('servers.')->group(function () {
        /**
         * Server detail
         */
        Route::prefix('server/{server}')->as('show')->group(function () {
            Route::get('/', 'ServerController@show');
            Route::get('banner.png', 'ServerController@banner')->name('.banner');
        });

        /**
         * Create & Store
         */
        Route::middleware('auth')->get('create', 'ServerController@create')->name('create');
        Route::middleware('auth')->post('store', 'ServerController@store')->name('store');

        /**
         * Servers
         */
        Route::get('servers/{params?}', 'ServerController@index')->name('index');
        Route::get('{params?}', 'RedirectController@index'); // @TEMP
    });

    /**
     * Blog
     */
    Route::get('blog/servers/{blog}', 'BlogController@redirect');
    Route::get('servers/blog/{blog}', 'BlogController@show')->name('servers.blog.show');
});

resources/views/admin/layouts/master.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <meta name="robots" content="noindex,nofollow,noarchive" />
    @if ($favicon = setting('site.favicon'))
    <link rel="shortcut icon" href="{{ $favicon }}" />
    @endif
    {{ LSEO::generate() }}
    <link rel="stylesheet" href="{{ mix('static/admin/css/admin.css') }}">
</head>

<body>
    <nav class="navbar navbar-expand-sm navbar-light">
        <div class="container">
            <a class="navbar-brand" href="{{ route('admin.overview') }}">{{ __('Dashboard') }}</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar"
                aria-controls="navbar" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbar">
                <ul class="navbar-nav mr-auto mt-2 mt-sm-0">
                    <li class="nav-item{{ ($rotueName = request()->route()->getName()) === 'admin.overview' ? ' active' : '' }}">
                        <a class="nav-link" href="{{ route('admin.overview') }}">{{ __('Overview') }}</a>
                    </li>
                    <li class="nav-item{{ Str::contains($rotueName, 'admin.servers.') ? ' active' : '' }}">
                        <a class="nav-link" href="{{ route('admin.servers.index') }}">{{ __('Servers') }}</a>
                    </li>
                    <li class="nav-item{{ Str::contains($rotueName, 'admin.settings.') ? ' active' : '' }}">
                        <a class="nav-link" href="{{ route('admin.settings.index') }}">{{ __('Settings') }}</a>
                    </li>
                </ul>
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="btn btn-sm btn-outline-secondary" href="{{ route('servers.index') }}"
                            target="_blank">{{ __('Go to site') }}</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="mb-5">
        @yield('content')
    </div>
    <script src="{{ mix('static/admin/js/admin.js') }}"></script>
    @stack('scripts')
</body>

</html>